[[plugins]]
package = "netlify-plugin-a11y"

  # required config
  checkPaths = ['/*'] # you can give an array of directories or paths to html files, that you want to run a11y checks on
  # # optional config
  resultMode = "warn" # is "error" by default
