#!/usr/bin/env ruby
# Modified from https://github.com/heroku/heroku-buildpack-static/blob/bde9522300fe5f1eb7513e7f2ee6731958987c23/scripts/config/make-htpasswd

HTPASSWD    = '/app/.htpasswd'
USERNAME    = ENV["BASIC_AUTH_USERNAME"]
PASSWORD    = ENV["BASIC_AUTH_PASSWORD"]

htpasswd    = "#{USERNAME}:#{PASSWORD}" unless (USERNAME.nil? || PASSWORD.nil?)

File.open(HTPASSWD, 'a') { |file| file.puts(htpasswd) } if !htpasswd.nil?