export const STRIPE_PUBLIC_KEY = process.env.GATSBY_STRIPE_PUBLIC_KEY;
export const STRIPE_PRODUCT_MONTHLY_DONATION_10 =
  process.env.GATSBY_STRIPE_PRODUCT_MONTHLY_DONATION_10;
export const STRIPE_PRODUCT_MONTHLY_DONATION_20 =
  process.env.GATSBY_STRIPE_PRODUCT_MONTHLY_DONATION_20;
export const STRIPE_PRODUCT_MONTHLY_DONATION_50 =
  process.env.GATSBY_STRIPE_PRODUCT_MONTHLY_DONATION_50;
export const SERVICE_API_URL = process.env.GATSBY_SERVICE_API_URL;
